(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&c(r)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();document.querySelectorAll(".faq-acc-el-trigger").forEach(s=>{s.addEventListener("click",()=>{const o=s.closest(".faq-acc-el"),n=o.querySelector(".faq-acc-el-descr-frame"),c=o.querySelector(".faq-img");o.classList.contains("open")?(o.classList.remove("open"),c==null||c.classList.remove("rotated"),n&&(n.style.maxHeight="0")):(o.classList.add("open"),c==null||c.classList.add("rotated"),n&&(n.style.maxHeight=n.scrollHeight+"px"))})});document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".menu-button"),o=s.querySelector(".icon"),n=document.querySelector(".modal"),c=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const r=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="3.5" stroke="#00FEFB" />
  <path d="M5.625 7.125H18.375M5.625 16.125H18.375M5.625 11.625H18.375" stroke="#FAFAFA" stroke-linecap="round" />
</svg>
    `,d=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0.5" y="0.5" width="23" height="23" rx="3.5" stroke="#00FEFB" />
  <path d="M5.25 5.25L12 12M12 12L5.25 18.75M12 12L18.75 18.75M12 12L18.75 5.25" stroke="#FAFAFA" stroke-linecap="round" stroke-linejoin="round" />
</svg>
    `;s.addEventListener("click",()=>{t=!t,o.innerHTML=t?d:r,t?a():i()}),c.forEach(f=>f.addEventListener("click",()=>{i(),o.innerHTML=r,t=!1})),window.addEventListener("scroll",u);function a(){n.style.display="block"}function i(){n.style.display="none"}function u(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll('a[href^="#"]').forEach(s=>{s.addEventListener("click",function(o){o.preventDefault();const n=this.getAttribute("href").substring(1),c=document.getElementById(n);if(c){const t=c.offsetTop-90;window.scrollTo({top:t,behavior:"smooth"})}})})});const l=document.querySelectorAll(".navigation-item");l.forEach(s=>{s.addEventListener("click",function(o){o.preventDefault(),l.forEach(n=>n.classList.remove("active")),this.classList.add("active")})});document.addEventListener("DOMContentLoaded",function(){const s=document.getElementById("cookie-popup"),o=document.getElementById("accept-cookies"),n=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(s.style.display="block"),o.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),s.style.display="none"}),n.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),s.style.display="none"})});
//# sourceMappingURL=index.js.map
